"""Smoke tests for cpp_capture_parser.

Uses synthetic D3D12 and Vulkan source that mimics Nsight's
Generate-C++-Capture emit style — short, straight-line, single-statement
per logical call. When real captured output is available, drop it into
``tests/data/`` and add a `test_real_*` case.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from nsight_graphics_mcp import cpp_capture_parser as ccp


def _build_root_sig_blob_v1(parameters: list[dict]) -> bytes:
    """Serialise a tiny D3D12 v1.0 root signature blob for testing.

    ``parameters`` items are either::

        {"type": "DESCRIPTOR_TABLE", "vis": 0,
         "ranges": [{"range_type": 0, "num_descriptors": 1,
                     "base_register": 0, "register_space": 0,
                     "offset": 0}, ...]}

        {"type": "32BIT_CONSTANTS", "vis": 5,
         "shader_register": 0, "register_space": 1, "num_32bit_values": 4}

        {"type": "CBV"|"SRV"|"UAV", "vis": 0,
         "shader_register": 2, "register_space": 0}
    """
    import struct

    PARAM_TYPE = {"DESCRIPTOR_TABLE": 0, "32BIT_CONSTANTS": 1, "CBV": 2, "SRV": 3, "UAV": 4}
    # Plan layout: header(24) + params(12 * N) + per-param payloads appended.
    header_size = 24
    param_stride = 12
    params_offset = header_size
    payload_offset = header_size + len(parameters) * param_stride

    out = bytearray()
    out += b"\x00" * payload_offset
    # Header (we'll patch after).
    struct.pack_into(
        "<IIIIII", out, 0,
        1,                          # version
        len(parameters),
        params_offset,
        0,                          # num_static_samplers
        0,                          # static_samplers_offset
        0,                          # flags
    )

    cursor = payload_offset
    for i, p in enumerate(parameters):
        ptype = PARAM_TYPE[p["type"]]
        vis = p["vis"]
        if p["type"] == "DESCRIPTOR_TABLE":
            ranges_offset = cursor + 8
            num_ranges = len(p["ranges"])
            # num_ranges DWORD + ranges_offset DWORD
            out += struct.pack("<II", num_ranges, ranges_offset)
            cursor += 8
            for r in p["ranges"]:
                out += struct.pack(
                    "<IIIII",
                    r["range_type"],
                    r["num_descriptors"],
                    r["base_register"],
                    r["register_space"],
                    r["offset"],
                )
                cursor += 20
            data_field = ranges_offset - 8  # the 8-byte table header offset
            # Restore param record: data_field is the offset to (num_ranges, ranges_offset)
            data_field = ranges_offset - 8
        elif p["type"] == "32BIT_CONSTANTS":
            data_field = cursor
            out += struct.pack(
                "<III", p["shader_register"], p["register_space"], p["num_32bit_values"]
            )
            cursor += 12
        else:  # CBV / SRV / UAV
            data_field = cursor
            out += struct.pack("<II", p["shader_register"], p["register_space"])
            cursor += 8
        struct.pack_into(
            "<III", out, params_offset + i * param_stride,
            ptype, vis, data_field,
        )
    return bytes(out)


D3D12_SAMPLE = textwrap.dedent(
    """\
    // Generated by NVIDIA Nsight Graphics
    void play_frame() {
        pCommandList->SetGraphicsRootSignature(g_RootSig_0);
        pCommandList->SetDescriptorHeaps(2, g_DescHeaps_0);
        pCommandList->SetPipelineState(g_PSO_4);
        pCommandList->SetGraphicsRootDescriptorTable(0, g_GpuDescHandle_3);
        pCommandList->SetGraphicsRootConstantBufferView(1, 0x12345678ULL);
        pCommandList->SetGraphicsRoot32BitConstants(2, 4, &g_Constants_7, 0);
        pCommandList->IASetVertexBuffers(0, 1, &g_VBV_2);
        pCommandList->IASetIndexBuffer(&g_IBV_8);
        pCommandList->OMSetRenderTargets(1, &g_RTV_5, FALSE, &g_DSV_6);
        pCommandList->DrawIndexedInstanced(36, 1, 0, 0, 0);
        // Should be skipped — not a cmd-list method
        pCommandList->AddRef();
    }
    """
)

VK_SAMPLE = textwrap.dedent(
    """\
    void play_frame(VkCommandBuffer cmd) {
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, g_Pipeline_0);
        vkCmdBindDescriptorSets(
            cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, g_Layout_1,
            0, 1, &g_DescSet_5,
            0, nullptr);
        vkCmdBindVertexBuffers(cmd, 0, 1, &g_VB_2, &g_VBOffset_2);
        vkCmdBindIndexBuffer(cmd, g_IB_3, 0, VK_INDEX_TYPE_UINT16);
        vkCmdPushConstants(cmd, g_Layout_1, VK_SHADER_STAGE_VERTEX_BIT, 0, 64, &g_PC_data);
        vkCmdDrawIndexed(cmd, 36, 1, 0, 0, 0);
    }
    """
)


def _write_project(tmp_path: Path) -> Path:
    proj = tmp_path / "GeneratedCpp"
    proj.mkdir()
    (proj / "d3d12.cpp").write_text(D3D12_SAMPLE, encoding="utf-8")
    (proj / "vulkan.cpp").write_text(VK_SAMPLE, encoding="utf-8")
    return proj


def test_split_args_handles_nesting_and_strings() -> None:
    raw = '0, &g_X, "a,b,(c)", {1, 2, {3, 4}}, foo<int, float>(1)'
    assert ccp.split_args(raw) == [
        "0", "&g_X", '"a,b,(c)"', "{1, 2, {3, 4}}", "foo<int, float>(1)"
    ]


def test_index_cpp_project_picks_up_both_apis(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    assert idx.record_count > 0
    assert idx.api_histogram.get("d3d12", 0) >= 9  # 10 cmd-list calls minus AddRef
    assert idx.api_histogram.get("vulkan", 0) == 6
    # The blacklisted AddRef should NOT have been indexed
    rows = ccp.query_calls(idx.db_path, name="AddRef")
    assert rows == []


def test_per_event_named_args_d3d12(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    # Find the SetGraphicsRootDescriptorTable call and confirm its named args.
    rows = ccp.query_calls(idx.db_path, name="SetGraphicsRootDescriptorTable")
    assert len(rows) == 1
    row = rows[0]
    assert row["named_args"]["root_param_index"] == "0"
    assert row["named_args"]["gpu_descriptor_handle"] == "g_GpuDescHandle_3"

    rows = ccp.query_calls(idx.db_path, name="DrawIndexedInstanced")
    assert len(rows) == 1
    args = rows[0]["named_args"]
    assert args["index_count_per_instance"] == "36"
    assert args["instance_count"] == "1"


def test_per_event_named_args_vulkan(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    rows = ccp.query_calls(idx.db_path, name="vkCmdBindDescriptorSets")
    assert len(rows) == 1
    a = rows[0]["named_args"]
    assert a["first_set"] == "0"
    assert a["descriptor_set_count"] == "1"
    assert a["p_descriptor_sets"] == "&g_DescSet_5"


def test_descriptor_bindings_reconstruction_d3d12(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    # Get the DrawIndexedInstanced event and reconstruct prior state
    draw = ccp.query_calls(idx.db_path, name="DrawIndexedInstanced")[0]
    state = ccp.descriptor_bindings_for_event(idx.db_path, draw["event_index"])
    d3 = state["d3d12"]
    assert d3["root_signature"]["value"] == "g_RootSig_0"
    assert d3["pipeline_state"]["value"] == "g_PSO_4"
    assert d3["vertex_buffers"]["views"] == "&g_VBV_2"
    assert d3["index_buffer"]["view"] == "&g_IBV_8"
    assert "0" in d3["root_params"]
    assert d3["root_params"]["0"]["call"] == "SetGraphicsRootDescriptorTable"
    assert "1" in d3["root_params"]
    assert d3["root_params"]["1"]["call"] == "SetGraphicsRootConstantBufferView"


def test_descriptor_bindings_reconstruction_vulkan(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    draw = ccp.query_calls(idx.db_path, name="vkCmdDrawIndexed")[0]
    state = ccp.descriptor_bindings_for_event(idx.db_path, draw["event_index"])
    vk = state["vulkan"]
    assert vk["pipeline"]["pipeline"] == "g_Pipeline_0"
    assert vk["vertex_buffers"]["p_buffers"] == "&g_VB_2"
    assert vk["index_buffer"]["buffer"] == "g_IB_3"
    assert "0" in vk["descriptor_sets"]
    assert vk["descriptor_sets"]["0"]["p_descriptor_sets"] == "&g_DescSet_5"


# ---------------------------------------------------------------------------
# Descriptor heap timeline + root signature blob parsing
# ---------------------------------------------------------------------------


def test_descriptor_heap_timeline_collects_by_heap(tmp_path: Path) -> None:
    proj = tmp_path / "heap_timeline"
    proj.mkdir()
    (proj / "x.cpp").write_text(
        "void play() {\n"
        "    pCommandList->SetDescriptorHeaps(2, g_DescHeaps_0);\n"
        "    pCommandList->SetGraphicsRootDescriptorTable(0, g_GpuDescHandle_3);\n"
        "    pCommandList->SetGraphicsRootDescriptorTable(0, g_GpuDescHandle_4);\n"
        "    pCommandList->SetPipelineState(g_PSO_1);\n"
        "    pCommandList->DrawInstanced(3, 1, 0, 0);\n"
        "}\n",
        encoding="utf-8",
    )
    idx = ccp.index_cpp_project(proj)
    out = ccp.descriptor_heap_timeline(idx.db_path)
    assert out["ok"]
    # Three descriptor-related calls: SetDescriptorHeaps + two SetGraphicsRootDescriptorTable
    fns = [e["function_name"] for e in out["timeline"]]
    assert "SetDescriptorHeaps" in fns
    assert fns.count("SetGraphicsRootDescriptorTable") == 2
    # by_heap_symbol should contain g_DescHeaps_0
    assert "g_DescHeaps_0" in out["by_heap_symbol"]


def test_parse_root_signature_blob_descriptor_table(tmp_path: Path) -> None:
    blob = _build_root_sig_blob_v1(
        [
            {
                "type": "DESCRIPTOR_TABLE",
                "vis": 5,  # PIXEL
                "ranges": [
                    {
                        "range_type": 0,         # SRV
                        "num_descriptors": 4,
                        "base_register": 0,      # t0
                        "register_space": 0,
                        "offset": 0,
                    },
                    {
                        "range_type": 3,         # SAMPLER
                        "num_descriptors": 1,
                        "base_register": 0,      # s0
                        "register_space": 0,
                        "offset": 4,
                    },
                ],
            },
            {
                "type": "32BIT_CONSTANTS",
                "vis": 5,
                "shader_register": 0,
                "register_space": 1,
                "num_32bit_values": 4,
            },
        ]
    )
    out = ccp.parse_root_signature_blob(blob)
    assert out["ok"]
    assert out["header"]["version"] == 1
    assert out["header"]["num_parameters"] == 2
    p0, p1 = out["parameters"]
    assert p0["type"] == "DESCRIPTOR_TABLE"
    assert p0["shader_visibility"] == "PIXEL"
    assert p0["num_ranges"] == 2
    assert p0["ranges"][0]["range_type"] == "SRV"
    assert p0["ranges"][0]["base_shader_register"] == 0
    assert p0["ranges"][1]["range_type"] == "SAMPLER"
    assert p1["type"] == "32BIT_CONSTANTS"
    assert p1["num_32bit_values"] == 4
    assert p1["register_space"] == 1


def test_find_register_for_root_parameter_resolves_t0(tmp_path: Path) -> None:
    blob = _build_root_sig_blob_v1(
        [
            {
                "type": "DESCRIPTOR_TABLE",
                "vis": 5,
                "ranges": [
                    {
                        "range_type": 0,
                        "num_descriptors": 4,
                        "base_register": 0,
                        "register_space": 0,
                        "offset": 0,
                    }
                ],
            },
        ]
    )
    rs = ccp.parse_root_signature_blob(blob)
    hit = ccp.find_register_for_root_parameter(
        rs, register_class="SRV", register=0, space=0
    )
    assert hit is not None
    assert hit["root_parameter_index"] == 0
    assert hit["range_type"] == "SRV"
    assert hit["base_shader_register"] == 0
    assert hit["num_descriptors"] == 4

    # Out-of-range register should not match.
    miss = ccp.find_register_for_root_parameter(
        rs, register_class="SRV", register=99
    )
    assert miss is None


def test_root_signature_summary_finds_blob_from_project(tmp_path: Path) -> None:
    blob = _build_root_sig_blob_v1(
        [
            {
                "type": "DESCRIPTOR_TABLE",
                "vis": 0,
                "ranges": [
                    {
                        "range_type": 0,
                        "num_descriptors": 1,
                        "base_register": 0,
                        "register_space": 0,
                        "offset": 0,
                    }
                ],
            }
        ]
    )
    proj = tmp_path / "rs_project"
    proj.mkdir()
    body = ", ".join(f"0x{b:02X}" for b in blob)
    (proj / "rs.cpp").write_text(
        f"static const unsigned char g_RootSig_blob_0[] = {{ {body} }};\n"
        "void CreateRoot(ID3D12Device* device) {\n"
        "    device->CreateRootSignature(0, g_RootSig_blob_0, sizeof(g_RootSig_blob_0), IID_PPV_ARGS(&g_RS_0));\n"
        "}\n",
        encoding="utf-8",
    )
    idx = ccp.index_cpp_project(proj)
    # The CreateRootSignature heuristic doesn't require pso_resolver to run.
    summary = ccp.root_signature_summary(idx.db_path, proj)
    assert summary["ok"]
    assert summary["blob_count"] >= 1
    rs0 = summary["root_signatures"][0]
    assert rs0["symbol"] == "g_RootSig_blob_0"
    assert rs0["parsed"]["ok"]
    assert rs0["parsed"]["header"]["num_parameters"] == 1


def test_multiline_call_is_folded(tmp_path: Path) -> None:
    """Nsight sometimes splits long calls across lines; the folder should
    join them so the regex still matches."""
    proj = tmp_path / "multiline"
    proj.mkdir()
    (proj / "x.cpp").write_text(
        "void f(VkCommandBuffer cmd) {\n"
        "    vkCmdBindDescriptorSets(cmd,\n"
        "        VK_PIPELINE_BIND_POINT_GRAPHICS,\n"
        "        g_Layout_1,\n"
        "        2,\n"
        "        1,\n"
        "        &g_DescSet_9,\n"
        "        0, nullptr);\n"
        "}\n",
        encoding="utf-8",
    )
    idx = ccp.index_cpp_project(proj)
    rows = ccp.query_calls(idx.db_path, name="vkCmdBindDescriptorSets")
    assert len(rows) == 1
    assert rows[0]["named_args"]["first_set"] == "2"
    assert rows[0]["named_args"]["p_descriptor_sets"] == "&g_DescSet_9"
