"""Smoke tests for cpp_capture_parser.

Uses synthetic D3D12 and Vulkan source that mimics Nsight's
Generate-C++-Capture emit style — short, straight-line, single-statement
per logical call. When real captured output is available, drop it into
``tests/data/`` and add a `test_real_*` case.
"""

from __future__ import annotations

import textwrap
from pathlib import Path

from nsight_graphics_mcp import cpp_capture_parser as ccp


D3D12_SAMPLE = textwrap.dedent(
    """\
    // Generated by NVIDIA Nsight Graphics
    void play_frame() {
        pCommandList->SetGraphicsRootSignature(g_RootSig_0);
        pCommandList->SetDescriptorHeaps(2, g_DescHeaps_0);
        pCommandList->SetPipelineState(g_PSO_4);
        pCommandList->SetGraphicsRootDescriptorTable(0, g_GpuDescHandle_3);
        pCommandList->SetGraphicsRootConstantBufferView(1, 0x12345678ULL);
        pCommandList->SetGraphicsRoot32BitConstants(2, 4, &g_Constants_7, 0);
        pCommandList->IASetVertexBuffers(0, 1, &g_VBV_2);
        pCommandList->IASetIndexBuffer(&g_IBV_8);
        pCommandList->OMSetRenderTargets(1, &g_RTV_5, FALSE, &g_DSV_6);
        pCommandList->DrawIndexedInstanced(36, 1, 0, 0, 0);
        // Should be skipped — not a cmd-list method
        pCommandList->AddRef();
    }
    """
)

VK_SAMPLE = textwrap.dedent(
    """\
    void play_frame(VkCommandBuffer cmd) {
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, g_Pipeline_0);
        vkCmdBindDescriptorSets(
            cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, g_Layout_1,
            0, 1, &g_DescSet_5,
            0, nullptr);
        vkCmdBindVertexBuffers(cmd, 0, 1, &g_VB_2, &g_VBOffset_2);
        vkCmdBindIndexBuffer(cmd, g_IB_3, 0, VK_INDEX_TYPE_UINT16);
        vkCmdPushConstants(cmd, g_Layout_1, VK_SHADER_STAGE_VERTEX_BIT, 0, 64, &g_PC_data);
        vkCmdDrawIndexed(cmd, 36, 1, 0, 0, 0);
    }
    """
)


def _write_project(tmp_path: Path) -> Path:
    proj = tmp_path / "GeneratedCpp"
    proj.mkdir()
    (proj / "d3d12.cpp").write_text(D3D12_SAMPLE, encoding="utf-8")
    (proj / "vulkan.cpp").write_text(VK_SAMPLE, encoding="utf-8")
    return proj


def test_split_args_handles_nesting_and_strings() -> None:
    raw = '0, &g_X, "a,b,(c)", {1, 2, {3, 4}}, foo<int, float>(1)'
    assert ccp.split_args(raw) == [
        "0", "&g_X", '"a,b,(c)"', "{1, 2, {3, 4}}", "foo<int, float>(1)"
    ]


def test_index_cpp_project_picks_up_both_apis(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    assert idx.record_count > 0
    assert idx.api_histogram.get("d3d12", 0) >= 9  # 10 cmd-list calls minus AddRef
    assert idx.api_histogram.get("vulkan", 0) == 6
    # The blacklisted AddRef should NOT have been indexed
    rows = ccp.query_calls(idx.db_path, name="AddRef")
    assert rows == []


def test_per_event_named_args_d3d12(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    # Find the SetGraphicsRootDescriptorTable call and confirm its named args.
    rows = ccp.query_calls(idx.db_path, name="SetGraphicsRootDescriptorTable")
    assert len(rows) == 1
    row = rows[0]
    assert row["named_args"]["root_param_index"] == "0"
    assert row["named_args"]["gpu_descriptor_handle"] == "g_GpuDescHandle_3"

    rows = ccp.query_calls(idx.db_path, name="DrawIndexedInstanced")
    assert len(rows) == 1
    args = rows[0]["named_args"]
    assert args["index_count_per_instance"] == "36"
    assert args["instance_count"] == "1"


def test_per_event_named_args_vulkan(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    rows = ccp.query_calls(idx.db_path, name="vkCmdBindDescriptorSets")
    assert len(rows) == 1
    a = rows[0]["named_args"]
    assert a["first_set"] == "0"
    assert a["descriptor_set_count"] == "1"
    assert a["p_descriptor_sets"] == "&g_DescSet_5"


def test_descriptor_bindings_reconstruction_d3d12(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    # Get the DrawIndexedInstanced event and reconstruct prior state
    draw = ccp.query_calls(idx.db_path, name="DrawIndexedInstanced")[0]
    state = ccp.descriptor_bindings_for_event(idx.db_path, draw["event_index"])
    d3 = state["d3d12"]
    assert d3["root_signature"]["value"] == "g_RootSig_0"
    assert d3["pipeline_state"]["value"] == "g_PSO_4"
    assert d3["vertex_buffers"]["views"] == "&g_VBV_2"
    assert d3["index_buffer"]["view"] == "&g_IBV_8"
    assert "0" in d3["root_params"]
    assert d3["root_params"]["0"]["call"] == "SetGraphicsRootDescriptorTable"
    assert "1" in d3["root_params"]
    assert d3["root_params"]["1"]["call"] == "SetGraphicsRootConstantBufferView"


def test_descriptor_bindings_reconstruction_vulkan(tmp_path: Path) -> None:
    proj = _write_project(tmp_path)
    idx = ccp.index_cpp_project(proj)
    draw = ccp.query_calls(idx.db_path, name="vkCmdDrawIndexed")[0]
    state = ccp.descriptor_bindings_for_event(idx.db_path, draw["event_index"])
    vk = state["vulkan"]
    assert vk["pipeline"]["pipeline"] == "g_Pipeline_0"
    assert vk["vertex_buffers"]["p_buffers"] == "&g_VB_2"
    assert vk["index_buffer"]["buffer"] == "g_IB_3"
    assert "0" in vk["descriptor_sets"]
    assert vk["descriptor_sets"]["0"]["p_descriptor_sets"] == "&g_DescSet_5"


def test_multiline_call_is_folded(tmp_path: Path) -> None:
    """Nsight sometimes splits long calls across lines; the folder should
    join them so the regex still matches."""
    proj = tmp_path / "multiline"
    proj.mkdir()
    (proj / "x.cpp").write_text(
        "void f(VkCommandBuffer cmd) {\n"
        "    vkCmdBindDescriptorSets(cmd,\n"
        "        VK_PIPELINE_BIND_POINT_GRAPHICS,\n"
        "        g_Layout_1,\n"
        "        2,\n"
        "        1,\n"
        "        &g_DescSet_9,\n"
        "        0, nullptr);\n"
        "}\n",
        encoding="utf-8",
    )
    idx = ccp.index_cpp_project(proj)
    rows = ccp.query_calls(idx.db_path, name="vkCmdBindDescriptorSets")
    assert len(rows) == 1
    assert rows[0]["named_args"]["first_set"] == "2"
    assert rows[0]["named_args"]["p_descriptor_sets"] == "&g_DescSet_9"
